/* lang.js */
const translations = {
    "en": {
        "nav_about": "About Me",
        "nav_projects": "Projects",
        "nav_path": "Career",
        "nav_contact": "Contact",
        "hero_greeting": "Hello, I'm",
        "hero_title": "Creative Developer",
        "hero_desc": "Building digital experiences with passion and precision.",
        "btn_projects": "View Projects",
        "btn_contact": "Contact Me",
        "about_title": "About Me",
        "about_text": "I am a passionate developer who learns fast and delivers high-quality projects. Since starting with Python I have quickly expanded my skills to C, Bash, Linux, frontend development, ESP32, and Node.js. I enjoy building creative and efficient solutions that combine speed, precision, and innovation.",
        "path_title": "My Path",
        "path_1_date": "2023",
        "path_1_title": "Started Programming",
        "path_1_desc": "Began my programming journey with Python, exploring the basics and building small projects.",
        "path_2_date": "2024",
        "path_2_title": "C, Bash & Linux",
        "path_2_desc": "Expanded my skills with C programming, Bash scripting, and mastering Linux terminal commands.",
        "path_3_date": "2025",
        "path_3_title": "Frontend Development",
        "path_3_desc": "Learned HTML, CSS, and JavaScript to create interactive and visually appealing web pages.",
        "path_4_date": "2025",
        "path_4_title": "First Website",
        "path_4_desc": "Launched my first website, applying my frontend skills in a real-world project.",
        "path_5_date": "2025",
        "path_5_title": "New Projects & Node.js",
        "path_5_desc": "Started developing two new projects and began learning backend development with Node.js.",
        "path_6_date": "Present",
        "path_6_title": "Continious Growth",
        "path_6_desc": "Constantly improving, building projects that combine creativity, speed, and quality.",
        "proj_title": "Projects",
        "proj_card_btn": "View",
        "contact_title": "Contact Me",
        "contact_name": "Name",
        "contact_email": "Email",
        "contact_msg": "Message",
        "contact_send": "Send Message",
        "footer_text": "© 2025 Azer Yusifzade. All rights reserved."
    },
    "az": {
        "nav_about": "Haqqımda",
        "nav_projects": "Layihələr",
        "nav_path": "Karyeram",
        "nav_contact": "Əlaqə",
        "hero_greeting": "Salam, mən",
        "hero_title": "Kreativ Developer",
        "hero_desc": "Rəqəmsal təcrübələri həvəs və dəqiqliklə qururam.",
        "btn_projects": "Layihələr",
        "btn_contact": "Mənimlə Əlaqə",
        "about_title": "Haqqımda",
        "about_text": "Mən sürətlə öyrənən və yüksək keyfiyyətli layihələr yaradan bir proqramçıyamm.Python ilə başladıqdan sonra biliklərimi tez bir zamanda C, Bash, Linux, frontend, ESP32 və Node.js sahələrinə genişləndirdim. Mən sürət, dəqiqlik və yaradıcılığı birləşdirən layihələr yaratmağı sevirəm.",
        "path_title": "Karyeryam",
        "path_1_date": "2023",
        "path_1_title": "Proqramlaşdırmaya Başladım",
        "path_1_desc": "Proqramlaşdırmaya Python ilə başlayaraq əsas bilikləri öyrəndim və kiçik layihələr yaratdım.",
        "path_2_date": "2024",
        "path_2_title": "C, Bash və Linux",
        "path_2_desc": "C proqramlaşdırma, Bash skriptləri və Linux terminal əmrləri üzrə biliklərimi genişləndirdim.",
        "path_3_date": "2025",
        "path_3_title": "Frontend İnkişafı",
        "path_3_desc": "İnteraktiv və vizual cəhətdən cəlbedici veb səhifələr yaratmaq üçün HTML, CSS və JavaScript öyrəndim.",
        "path_4_date": "2025",
        "path_4_title": "İlk Veb Sayt",
        "path_4_desc": "İlk veb saytımı işə saldım və frontend bacarıqlarımı real layihədə tətbiq etdim.",
        "path_5_date": "2025",
        "path_5_title": "Yeni Layihələr & Node.js",
        "path_5_desc": "İki yeni layihə üzərində işləməyə başladım və Node.js ilə backend inkişafını öyrənməyə başladım.",
        "path_6_date": "Hazırkı Vaxt",
        "path_6_title": "Davamlı İnkişaf",
        "path_6_desc": "Daim öyrənirəm və yaradıcılıq, sürət və keyfiyyəti birləşdirən layihələr hazırlayıram.",
        "proj_title": "Layihələr",
        "proj_card_btn": "Bax",
        "contact_title": "Əlaqə",
        "contact_name": "Ad",
        "contact_email": "E-poçt",
        "contact_msg": "Mesaj",
        "contact_send": "Göndər",
        "footer_text": "© 2025 Azer Yusifzade. Bütün hüquqlar qorunur."
    },
    "ru": {
        "nav_about": "Обо мне",
        "nav_projects": "Проекты",
        "nav_path": "Карьера",
        "nav_contact": "Контакты",
        "hero_greeting": "Привет, я",
        "hero_title": "Креативный Разработчик",
        "hero_desc": "Создаю цифровые продукты со страстью и точностью.",
        "btn_projects": "Проекты",
        "btn_contact": "Связаться",
        "about_title": "Обо мне",
        "about_text": "Я разработчик, который быстро учится и создаёт качественные проекты. Начиная с Python, я быстро расширил свои навыки в C, Bash, Linux, фронтенде, ESP32 и Node.js. Мне нравится создавать проекты, где сочетаются скорость, точность и креативность.",
        "path_title": "Мой Путь",
        "path_1_date": "2023",
        "path_1_title": "Начало программирования",
        "path_1_desc": "Начал изучать программирование с Python, осваивая основы и создавая небольшие проекты.",
        "path_2_date": "2024",
        "path_2_title": "C, Bash и Linux",
        "path_2_desc": "Расширил свои навыки, изучив C, Bash и команды терминала Linux.",
        "path_3_date": "2025",
        "path_3_title": "Frontend-разработка",
        "path_3_desc": "Освоил HTML, CSS и JavaScript для создания интерактивных и привлекательных веб-страниц.",
        "path_4_date": "2025",
        "path_4_title": "Первый веб-сайт",
        "path_4_desc": "Запустил свой первый веб-сайт, применяя навыки frontend в реальном проекте.",
        "path_5_date": "2025",
        "path_5_title": "Новые проекты & Node.js",
        "path_5_desc": "Начал разработку двух новых проектов и изучение backend с Node.js.",
        "path_6_date": "Настоящее",
        "path_6_title": "Постоянный рост",
        "path_6_desc": "Постоянно развиваюсь, создавая проекты, объединяющие креативность, скорость и качество.",
        "proj_title": "Проекты",
        "proj_card_btn": "Смотреть",
        "contact_title": "Контакты",
        "contact_name": "Имя",
        "contact_email": "Email",
        "contact_msg": "Сообщение",
        "contact_send": "Отправить",
        "footer_text": "© 2025 Azer Yusifzade. Все права защищены."
    }
};